[package]
name = "whippyunits"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["full"] }
libm = "0.2"
whippyunits-proc-macros = { path = "./proc-macros" }

[dev-dependencies]
trybuild = "1.0"

[[example]]
name = "proc_macro_usage"
path = "examples/proc_macro_usage.rs"

[features]
default = ["strict"]
strict = []
smaller_wins = []
left_hand_wins = []

[lib]
name = "whippyunits"
path = "src/lib.rs"



[profile.dev]
incremental = false

[profile.release]
incremental = false 